{{- if or .Values.rbac.pspEnabled .Values.rbac.sccEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
{{- if .Values.rbac.pspEnabled }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "loki.fullname" . }}
{{- end }}
{{- if .Values.rbac.sccEnabled }}
rules:
- apiGroups: 
  - security.openshift.io
  resources: 
  - securitycontextconstraints
  verbs: 
  - use
  resourceNames:
  - {{ include "loki.fullname" . }}
{{- end }}
{{- if and .Values.ruler.enabled .Values.ruler.sidecar.enabled .Values.ruler.sidecar.rbac.namespaced }}
  {{- if or (eq .Values.ruler.sidecar.rules.resource "both") (eq .Values.ruler.sidecar.rules.resource "configmap") }}
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- if or (eq .Values.ruler.sidecar.rules.resource "both") (eq .Values.ruler.sidecar.rules.resource "secret") }}
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  {{- end }}
{{- end}}
{{- end }}
