apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.ingesterFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.ingesterSelectorLabels" . | nindent 4 }}
    prometheus.io/service-monitor: "false"
  {{- with .Values.loki.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - appProtocol: tcp  
      name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loki.ingesterSelectorLabels" . | nindent 4 }}
